app/Http/Controllers/Api/HeroesController.php, app/Http/Controllers/Api/NovelsController.php, resources/js/components/items/HeroImgComponent.vue, resources/js/components/pages/Hero.vue, resources/js/components/pages/Top.vue, resources/js/router.js, routes/api.php
- 主人公の画像とidをDBから取得
- Novelsテーブルからマッチした主人公の小説タイトルを表示
=> 主人公のデータをDBから取得

app/Http/Controllers/Api/NovelsController.php, resources/js/components/items/HeaderComponent.vue, resources/js/components/pages/Hero.vue, resources/js/components/pages/NovelTitle.vue, resources/js/router.js, routes/api.php
- タイトル入力ページを作成
- 執筆ボタンからの遷移にhero_idを持たせる
- タイトル入力後にエピソード執筆ページへ遷移
=> 執筆ボタンで小説タイトル入力画面へ遷移

app/Http/Controllers/Api/EpisodesController.php, app/Http/Controllers/Api/NovelsController.php, resources/js/components/pages/Hero.vue, resources/js/components/pages/NovelTitle.vue, resources/js/components/pages/Top.vue, resources/js/components/pages/Write.vue, resources/js/router.js, routes/api.php
- postしたnovel_idを取得してパスに入れて遷移させた
=> タイトル保存→エピソード執筆ページへの遷移（thanks Matsuo）

app/Http/Controllers/Api/NovelsController.php, resources/js/components/pages/NovelTitle.vue, resources/js/components/pages/Write.vue
- 執筆ページで小説idをpostできるようにした
　→エピソードと小説と主人公が紐づいた
=> 執筆ページで小説idもpostする

app/Http/Controllers/Api/HeroesController.php, app/Http/Controllers/Api/NovelsController.php, app/Http/Controllers/Auth/LoginController.php, app/Http/Kernel.php, database/migrations/2020_03_27_060137_create_novels_table.php, database/seeds/NovelsTableSeeder.php, resources/js/components/App.vue, resources/js/components/pages/NovelTitle.vue, resources/js/router.js, resources/views/index.blade.php, resources/views/layouts/app.blade.php, routes/api.php, routes/web.php
- Kernel.phpをいじくらないといけなかったとこでハマった
=> ユーザー情報をコントローラーで取得

app/Http/Controllers/Api/EpisodesController.php, app/Http/Controllers/Api/NovelsController.php, database/seeds/EpisodesTableSeeder.php, resources/js/components/pages/Hero.vue, resources/js/components/pages/Read.vue, resources/js/router.js, routes/api.php
- 読書ページへのリンク
- 読書ページでuserテーブル&novelsテーブル&episodesテーブルにDB接続してデータを取得
=> 主人公ページから読書ページへいけるようになった

app/Http/Controllers/Api/NovelsController.php, resources/js/components/pages/Write.vue, resources/js/components/pages/profiles/Writedbooks.vue, resources/js/components/pages/profiles/Writingbooks.vue, routes/api.php
- プロフィールページで公開/非公開を切り替えられるようになった
=> 公開/非公開のボタン

database/seeds/NovelsTableSeeder.php, resources/js/components/pages/ReadFirstSentence.vue, resources/js/components/pages/Top.vue, resources/js/router.js
=> 主人公ページからのルーティングを変更

app/Http/Controllers/Api/NovelsController.php, database/migrations/2020_03_27_060137_create_novels_table.php, database/seeds/NovelsTableSeeder.php, resources/js/components/pages/Hero.vue, resources/js/components/pages/WriteFirstSentence.vue, resources/js/router.js, routes/api.php
-  主人公ページから遷移
- 真ん中に縦書きでテキストエリア
- 句読点で完了ボタンを発生
- 続きを書くページへ遷移
=> 一文目を書くページを追加

app/Http/Controllers/Api/EpisodesController.php, app/Http/Controllers/Api/NovelsController.php, resources/js/components/App.vue, resources/js/components/pages/Write.vue, resources/js/components/pages/WriteFirstSentence.vue, resources/views/index.blade.php
- 縦書きの実装
- 一文目を保存しつつ表示
- タイトルを保存
- プレースホルダーを実装
=> 執筆ページを縦書きで実装

package-lock.json, package.json, public/css/app.css, resources/js/components/App.vue, resources/js/components/items/HeaderComponent.vue, resources/js/components/pages/Hero.vue, resources/js/components/pages/Write.vue, resources/js/components/pages/WriteFirstSentence.vue, resources/sass/app.scss
=> 執筆前のモーダル設置

app/Http/Controllers/Api/NovelsController.php, resources/js/components/pages/PaperEdit.vue, resources/js/components/pages/ReadFirstSentence.vue
- 横スライドのカルーセルで一文目を表示
- 文章そのものをリンクにしてます
- ランダムにはしてません
=> 最初の一文ページ作成

resources/js/components/pages/Read.vue, resources/js/components/pages/ReadFirstSentence.vue, resources/js/components/pages/Top.vue, resources/js/components/pages/Write.vue
- 読書ページに縦書きのテキストを表示
- 一文表示の前にモーダル入れた
- テキストが改行されないで四角からはみ出るバグあり
=> 読書ページでテキストを取得して表示

app/Http/Controllers/Api/EpisodesController.php, app/Http/Controllers/Api/NovelsController.php, database/migrations/2020_03_27_060137_create_episodes_table.php, database/seeds/EpisodesTableSeeder.php, resources/js/components/pages/PaperEdit.vue, resources/js/components/pages/Write.vue, resources/js/components/pages/WriteTitle.vue, resources/js/router.js, routes/api.php
-  タイトル用のペーパーを編集ページに固定配置
- 編集できるようにした
- UIダメダメ
=> タイトル入力用ペーパーを設置

package-lock.json, package.json, resources/js/components/pages/PaperEdit.vue
- vue-grid-layoutの導入
- タイトルページだけスタイル変更
- ペーパーが12個以上になるとレイアウト崩れる
=> 編集ページのレイアウト変更

app/Http/Controllers/Api/NovelsController.php, resources/js/components/pages/Profile.vue, resources/js/components/pages/profiles/Writedbooks.vue, resources/js/components/pages/profiles/Writingbooks.vue, resources/js/router.js
- 公開/非公開ページに分けて、主人公の画像と一緒に表示
- 公開ボタンだけ設置
- プロフィールページ来たら公開してる小説一覧にリダイレクト設定
=> プロフィールのUI変更

app/Http/Controllers/Api/EpisodesController.php, app/Http/Controllers/Api/NovelsController.php, database/migrations/2020_03_27_060137_create_novels_table.php, database/seeds/EpisodesTableSeeder.php, database/seeds/NovelsTableSeeder.php, resources/js/components/pages/PaperEdit.vue, resources/js/components/pages/Write.vue, resources/js/components/pages/WriteFirstSentence.vue, resources/js/router.js, resources/js/store/index.js, routes/api.php
- ユーザーが書いたペーパーの順序を入れるカラムを追加
- それに合わせてapiを修正
=> 編集ページのパスを変更しました

app/Http/Controllers/Api/PaperNovelsController.php, resources/js/components/pages/Profile.vue, resources/js/components/pages/profiles/PaperNovelClosed.vue, resources/js/components/pages/profiles/PaperNovelOpened.vue, resources/js/router.js, routes/api.php
- ファイル名の変更
- 変数名の変更
- APIの処理書き換え
=> プロフィールページのデバッグ

app/Http/Controllers/Api/StoryPapersController.php, resources/js/components/pages/EditPaperNovel.vue, resources/js/components/pages/WriteStoryPaper.vue, resources/js/components/pages/WriteTitlePaper.vue, resources/js/components/pages/profiles/PaperNovelClosed.vue, resources/js/components/pages/profiles/PaperNovelOpened.vue, routes/api.php
- プロフィールページに編集ボタンを設置して編集ページへリンク
- 取得するデータがバグってたので修正した
=> プロフィールから編集ページへ飛べるようになった

app/Http/Controllers/Api/PaperNovelsController.php, app/Http/Controllers/Api/StoryPapersController.php, resources/js/components/pages/EditPaperNovel.vue, resources/js/components/pages/EditStoryPaper.vue, resources/js/components/pages/WriteFirstSentence.vue, resources/js/router.js, routes/api.php
- ペーパーノベル編集ページから、ストーリーペーパをクリックして内容を更新できるようになりました
=> ストーリーペーパーも編集できるようになった

resources/js/components/items/HeaderComponent.vue
=> ログアウト機能付けました

resources/js/components/pages/EditPaperNovel.vue
- ペーパー編集ページからストーリーペーパー追加するとこバグってたので修正
=> ストーリーペーパー追加機能のデバッグ

resources/js/components/App.vue, resources/js/components/pages/Top.vue
app.vueにstyle追加
top.vueのp{color:black;}削除
=> フォントcssを修正中

resources/js/components/App.vue, resources/js/components/items/HeaderComponent.vue, resources/js/components/pages/EditPaperNovel.vue, resources/js/components/pages/EditStoryPaper.vue, resources/js/components/pages/Hero.vue, resources/js/components/pages/Profile.vue, resources/js/components/pages/ReadFirstSentence.vue, resources/js/components/pages/ReadPaper.vue, resources/js/components/pages/Top.vue, resources/js/components/pages/WriteFirstSentence.vue, resources/js/components/pages/WriteStoryPaper.vue, resources/js/components/pages/WriteTitlePaper.vue, resources/js/components/pages/profiles/PaperNovelClosed.vue, resources/js/components/pages/profiles/PaperNovelOpened.vue
フォントの色 #333333に変更
クロームでのフォーカス時の青い四角を消した
=> フォントの色変更とoutline:none

resources/js/components/pages/WriteFirstSentence.vue, resources/js/components/pages/WriteStoryPaper.vue
- 開発中のため行数を表示してます
- 17行でエンターキーを無効にしました
- UIは整ってません
=> 17行で制御しました

resources/js/components/pages/WriteStoryPaper.vue
- CSSで高さと文字数計算して1行に32文字になるようにしました
- ローマ字は大きさ違うので32文字以上入っちゃいます
- レスポンシブ対応必須です。。
=> cssで32文字制限しました

app/Http/Controllers/Api/MarkersController.php, app/Marker.php, database/migrations/2014_10_12_000000_create_users_table.php, database/migrations/2020_04_14_023157_create_markers_table.php, database/seeds/UsersTableSeeder.php
- markersテーブルを作成
- usersテーブルに、user_nameとbioのカラムを追加
=> マーカーテーブル用意&ユーザーテーブル追加

app/Http/Controllers/Api/MarkersController.php, resources/js/components/pages/ReadPaper.vue, resources/js/components/pages/WriteStoryPaper.vue, routes/api.php
- 選択したテキストと小説の情報をDBにpost
- とりあえずだっせえボタンにしてます
=> マーカー機能つきました

app/Http/Controllers/Api/MarkersController.php, resources/js/components/pages/Profile.vue, resources/js/components/pages/profiles/MarkedText.vue, resources/js/router.js
- プロフィールにマークしたテキストを表示するコンポーネント設置
- クリックでその小説に飛べる
=> プロフィールにマークしたテキスト&リンク設置

app/Http/Controllers/Api/MarkersController.php, resources/js/components/pages/ReadPaper.vue, routes/api.php
- マークされてる数を取得するAPI作成
- ReadPaperページにテストで表示
=> マークされてる数を表示

app/Http/Controllers/Api/UsersController.php, resources/js/components/pages/Profile.vue, routes/api.php
=> プロフィール編集できるようになった

app/Http/Controllers/Api/PaperNovelsController.php, resources/js/components/pages/profiles/PaperNovelOpened.vue, routes/api.php
- 小説の削除機能付けました
- プロフィールから削除できます
- モーダルで確認を入れてます
=> 小説の削除機能付けました

app/Http/Controllers/Api/PaperNovelsController.php, app/Http/Controllers/Api/UsersController.php, resources/js/components/items/HeaderComponent.vue, resources/js/components/pages/Profile.vue, resources/js/components/pages/ReadPaper.vue, resources/js/components/pages/profiles/PaperNovelOpened.vue, resources/js/router.js, routes/api.php
- 読書ページに作者へのリンクを設置
- 公開中の小説だけ見れるようにした
- マイページの時だけ、編集ボタンとかが出る
=> 他人のプロフィールページを見れるようにしました

app/Http/Controllers/Auth/RegisterController.php, app/User.php, database/migrations/2014_10_12_000000_create_users_table.php, resources/views/auth/register.blade.php
=> ユーザーネームの登録を必須にした

app/Http/Controllers/Api/PaperNovelsController.php, resources/js/components/pages/ReadPaper.vue
=> 非公開ページのパス入力したらTopへリダイレクト

resources/js/components/pages/EditPaperNovel.vue, resources/js/components/pages/ReadPaper.vue
-編集ページで、 最初の一文ペーパーに【最初の一文】と表記 
- 読書ページで最初の一文ペーパー出ちゃうのをデバッグ
=> 読書ページのデバッグ

resources/js/components/pages/ReadFirstSentence.vue
ReadFirstSentenceのカルーセルにスワイプ追加
=> ReadFirstSentenceスワイプ追加

resources/js/components/pages/EditPaperNovel.vue, resources/js/components/pages/profiles/PaperNovelClosed.vue
=> EditPaperページで、もじがはみ出るのを防ぐ

app/Http/Controllers/Api/UsersController.php, app/Http/Kernel.php, resources/js/components/pages/EditPaperNovel.vue, resources/js/components/pages/Profile.vue
- APIのリクエスト制限を60回/1分→600回/1分へ変更
- 編集のバグ解消
=> プロフィール編集のデバッグ

resources/js/components/pages/ReadFirstSentence.vue
ReadFirstSentence32行で改行するようにした
=> ReadFirstSentence32行制御

resources/js/components/App.vue, resources/js/components/pages/Profile.vue, resources/views/index.blade.php
=> プロフィールページでリロードするとタブの位置おかしくなるバグ解消

app/Http/Controllers/Api/PaperNovelsController.php, app/Http/Controllers/Api/StoryPapersController.php, resources/js/components/pages/EditPaperNovel.vue, resources/js/components/pages/EditStoryPaper.vue, resources/js/components/pages/WriteStoryPaper.vue, routes/api.php
- 最初のページが更新されたタイミングで、最初の一文を取得してDB更新
=> 最初の一文が更新されたらDBも更新

resources/js/components/items/HeaderComponent.vue, resources/js/components/pages/EditPaperNovel.vue, resources/js/components/pages/EditStoryPaper.vue, resources/js/components/pages/ReadPaper.vue, resources/js/components/pages/WriteFirstSentence.vue, resources/js/components/pages/WriteStoryPaper.vue
- 文字コードをまとめて保存
- 表示するときは<br>に変換する
=> 改行の処理も保存できるようになった

resources/js/components/pages/Complete.vue, resources/js/components/pages/EditPaperNovel.vue, resources/js/router.js
- 編集ページからアイコンクリックで本完成ページにリンク
- ペーパー追加ボタンのUIを変更
=> 本になりましたページを作成

resources/js/components/items/HeaderComponent.vue, resources/js/components/items/LoginModal.vue
- ヘッダーにログイン用モーダルを表示するアイコンを設置
- ログインと新規登録のモーダルを設置
=> ログイン用のモーダルを準備

app/Bookmark.php, app/Http/Controllers/Api/BookmarksController.php, database/migrations/2020_04_25_065636_create_bookmarks_table.php, resources/js/components/pages/Profile.vue, resources/js/components/pages/ReadPaper.vue, resources/js/components/pages/profiles/Bookmarks.vue, resources/js/components/pages/profiles/PaperNovelOpened.vue, resources/js/router.js, routes/api.php
- 読書ページからブックマークできる
- マイページで見れる
- リンクとべる
- 削除できる
=> ブックマーク機能つきました

app/Http/Controllers/Api/UsersController.php, resources/js/components/items/HeaderComponent.vue, resources/js/components/items/LoginModal.vue, resources/js/components/pages/SelectWrite.vue, resources/js/store/index.js
- 書くページにいったらモーダル表示
- バツボタンでtopへリダイレクトして先はいけないようにする
=> ログインしてない奴は書くページでログイン画面表示

resources/js/components/items/LoginModal.vue
=> ログイン画面のバリデーション付けた

resources/js/components/items/Hint.vue, resources/js/components/pages/Top.vue, resources/js/components/pages/WriteFirstSentence.vue
- WriteFirstSentenceページにヒントアイコンを表示
- クリックでモーダル表示
- 質問項目によってテーブルのカラム数変わるので、保存機能は後付けします。
=> ヒントのモーダルを設置

resources/js/components/App.vue, resources/js/components/items/FooterComponent.vue, resources/js/components/items/HeaderComponent.vue
・items/FooterComponent.vue作成
・items/HeaderComponent.vueのスマホ時のアイコン非表示設定
・ログイン、ログアウトアイコンは検証時使用する為一旦残した
=> フッター作成、ヘッダーUI修正

package-lock.json, package.json, resources/js/app.js, resources/js/components/pages/ReadPaper.vue, resources/js/turn.js
- turn.jsの導入
- タイトルから読める
- UIはまだ
- マーキングができなくなってる
=> turn.jsに半分勝利

public/img/charactors/CharacterStayHome02.svg
・キャラだけじゃなくて吹き出し部分にもカーソルが乗せられるようになった
=> 吹き出しにもカーソルが乗せられるようになった

resources/js/components/items/HeaderComponent.vue, resources/js/components/pages/EditPaperNovel.vue
- アイコン設置（「完成」と「追加」と「ヒント（未実装）」）
- ページネーション機能つけました
=> 小説編集ページがだいぶ良くなったと思います

resources/js/components/pages/EditPaperNovel.vue, resources/js/components/pages/profiles/PaperNovelClosed.vue, resources/js/components/pages/profiles/PaperNovelOpened.vue
=> マイページの編集ボタンをホバーで表示

app/Http/Controllers/Api/PaperNovelsController.php, resources/js/components/pages/ReadFirstSentence.vue, resources/js/components/pages/WriteFirstSentence.vue, resources/js/components/pages/WriteStoryPaper.vue
- タイトルと第一文をカードにして並べた
- 最新の20件のみにしてます
=> 主人公から新着順で探す

resources/js/components/pages/EditPaperNovel.vue, resources/js/components/pages/EditStoryPaper.vue, resources/js/components/pages/WriteStoryPaper.vue, resources/js/components/pages/profiles/PaperNovelClosed.vue
- アイコンを左に配置
- アイコンの機能つけた
- ヒント
- 17行制御が完全じゃない
- 矢印の挙動を変えたい・・・
=> 書くページのUI整えました

app/Http/Controllers/Api/BookmarksController.php, resources/js/components/pages/ReadPaper.vue, resources/js/components/pages/profiles/Bookmarks.vue, routes/api.php
- UIをちょっと整えた
- ブックマークとマークをアイコンにした
=> 読書ページのUIを変更

app/Hint.php, app/Http/Controllers/Api/HintsController.php, database/migrations/2020_04_30_092845_create_hints_table.php, resources/js/components/items/HeaderComponent.vue, resources/js/components/items/Hint.vue, resources/js/components/pages/EditStoryPaper.vue, resources/js/components/pages/Profile.vue, resources/js/components/pages/ReadPaper.vue, routes/api.php
- ヒント機能をつけて保存できるようにした
- ログアウトボタンを編集ページに仮でつけた
- ログインしてる状態だったらログインアイコンを見せないようにした
=> ヒント機能実装&ログアウトボタンを編集ページに仮実装

resources/js/components/pages/EditStoryPaper.vue
-  執筆ページでテキストを入力してなかったらモーダルを表示
=> テキストのバリデーション

app/Http/Controllers/Api/StoryPapersController.php, resources/js/components/pages/Complete.vue, resources/js/components/pages/EditNovel.vue, resources/js/components/pages/EditStoryPaper.vue, resources/js/components/pages/Profile.vue, resources/js/components/pages/profiles/PaperNovelClosed.vue, resources/js/components/pages/profiles/PaperNovelOpened.vue, resources/js/router.js
- 小説編集ページのUIを横にしました
- デザインは何もしてないです
=> 小説編集ページのUI変更

resources/js/components/items/HeaderComponent.vue, resources/js/components/pages/SelectHero.vue, resources/js/router.js
- 書くページをTOPに変更
- ヘッダーの順番変更
- 試しにTOPに文言追加
=> ルーティングとヘッダーとTOPの変更

app/Http/Controllers/Api/StoryPapersController.php, resources/js/components/items/HeaderComponent.vue, resources/js/components/pages/EditStoryPaper.vue
- エディター の背景変更
- 文字数を5000字に制限(アラート出るようにした)
=> エディターの文字数制限

resources/js/components/items/Hint.vue, resources/js/components/pages/EditNovel.vue, resources/js/components/pages/EditStoryPaper.vue, resources/js/components/pages/WriteTitle.vue
- エディター のリンク修正
- レイアウト修正
- プレビュー
=> エディターのリンク修正

resources/js/components/pages/Profile.vue
=> マイページのUI変更

app/Http/Controllers/Api/BookmarksController.php, resources/js/components/pages/Bookmark.vue
=> ブックマークページに最初の50文字表示

resources/js/components/pages/Bookmark.vue, resources/js/components/pages/Complete.vue, resources/js/components/pages/EditNovel.vue, resources/js/components/pages/FindStory.vue, resources/js/components/pages/WriteTitlePaper.vue
・エピソード編集ページUI仮完成
・タイトル編集ページUI完成
・完成ページUI完成（リンク未完成）
・タイムラインUI仮完成
=> 執筆、編集、完成ページ、タイムラインUI仮完成

resources/js/components/pages/Bookmark.vue
・額縁＋本イラストを並べた
・タイトル部分にタイトルが入るような感じにした
=> ブックページ少し進んだ

resources/js/components/items/Hint.vue, resources/js/components/pages/WriteTitle.vue
=> 主人公選択後にヒントモーダルを出す

resources/js/components/items/Hint.vue, resources/js/components/pages/EditNovel.vue, resources/js/components/pages/EditStoryPaper.vue
=> エピソード削除機能追加

package-lock.json, package.json, resources/js/components/items/Hint.vue, resources/js/components/pages/WriteTitle.vue
- タイトルページをスマホサイズで横書きに変更
- ボタンなども再配置
=> タイトル執筆ページのレスポンシブ

resources/js/components/items/Hint.vue, resources/js/components/pages/EditStoryPaper.vue, resources/js/components/pages/Profile.vue, resources/js/components/pages/ReadPaper.vue, resources/js/components/pages/SelectHero.vue, resources/js/components/pages/WriteTitle.vue, resources/js/components/pages/profiles/PaperNovelOpened.vue
=> マイページUI等修正

resources/js/components/pages/EditNovel.vue
=> エピソード編集ページスマホ対応
